// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY-M3AYWBDMuXrbL8ACw3l2UPbKRQBw90',
    appId: '1:838827221992:android:a69afa74f3fb04b465fa5d',
    messagingSenderId: '838827221992',
    projectId: 'e-commerce-app-5126b',
    storageBucket: 'e-commerce-app-5126b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7fJssIRklbl7J34hEjWLqrWR83sSvr2g',
    appId: '1:838827221992:ios:a3ac56b77bba2b2665fa5d',
    messagingSenderId: '838827221992',
    projectId: 'e-commerce-app-5126b',
    storageBucket: 'e-commerce-app-5126b.firebasestorage.app',
    iosClientId: '838827221992-7kufkapbs8k9r77h9jfob5r4dokbhjqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabHeBlzwLshdt3y7ywU0UTRnyLnoNoyA',
    appId: '1:838827221992:web:2f57e8262de4214165fa5d',
    messagingSenderId: '838827221992',
    projectId: 'e-commerce-app-5126b',
    authDomain: 'e-commerce-app-5126b.firebaseapp.com',
    storageBucket: 'e-commerce-app-5126b.firebasestorage.app',
    measurementId: 'G-FVSH0J5153',
  );

}